/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "sumator.v:29" *)
module adder(x, y, s);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  (* src = "sumator.v:47|sumator.v:5" *)
  wire \G1.h ;
  (* src = "sumator.v:47|sumator.v:2" *)
  wire \G1.x ;
  (* src = "sumator.v:47|sumator.v:2" *)
  wire \G1.y ;
  (* src = "sumator.v:48|sumator.v:2" *)
  wire \G2.x ;
  (* src = "sumator.v:48|sumator.v:2" *)
  wire \G2.y ;
  (* src = "sumator.v:49|sumator.v:2" *)
  wire \G3.x ;
  (* src = "sumator.v:49|sumator.v:2" *)
  wire \G3.y ;
  (* src = "sumator.v:50|sumator.v:2" *)
  wire \G4.x ;
  (* src = "sumator.v:50|sumator.v:2" *)
  wire \G4.y ;
  (* src = "sumator.v:51|sumator.v:2" *)
  wire \G5.x ;
  (* src = "sumator.v:51|sumator.v:2" *)
  wire \G5.y ;
  (* src = "sumator.v:52|sumator.v:2" *)
  wire \G6.x ;
  (* src = "sumator.v:52|sumator.v:2" *)
  wire \G6.y ;
  (* src = "sumator.v:90|sumator.v:14" *)
  wire \P5_1.Gij ;
  (* src = "sumator.v:66|sumator.v:22" *)
  wire \S1.s ;
  (* src = "sumator.v:73|sumator.v:22" *)
  wire \S2.s ;
  (* src = "sumator.v:77|sumator.v:22" *)
  wire \S3.s ;
  (* src = "sumator.v:82|sumator.v:22" *)
  wire \S4.s ;
  (* src = "sumator.v:86|sumator.v:22" *)
  wire \S5.s ;
  (* src = "sumator.v:37" *)
  (* unused_bits = "1 2 3 4 5" *)
  wire [5:0] g;
  (* src = "sumator.v:35" *)
  (* unused_bits = "1 2 3 4 5" *)
  wire [5:0] h;
  (* src = "sumator.v:36" *)
  (* unused_bits = "1 2 3 4 5" *)
  wire [5:0] p;
  (* src = "sumator.v:33" *)
  output [6:0] s;
  (* src = "sumator.v:31" *)
  input [5:0] x;
  (* src = "sumator.v:32" *)
  input [5:0] y;
  assign \S1.s  = _01_ ^ _00_;
  assign \G1.h  = y[0] ^ x[0];
  assign _02_ = ~(y[2] ^ x[2]);
  assign _03_ = y[1] & x[1];
  assign _04_ = y[1] | x[1];
  assign _05_ = ~((_04_ & _01_) | _03_);
  assign \S2.s  = _05_ ^ _02_;
  assign _06_ = y[3] ^ x[3];
  assign _07_ = y[2] & x[2];
  assign _08_ = y[2] | x[2];
  assign _09_ = _08_ & ~(_05_);
  assign _10_ = _09_ | _07_;
  assign \S3.s  = _10_ ^ _06_;
  assign _11_ = y[4] ^ x[4];
  assign _12_ = y[3] & x[3];
  assign _13_ = y[3] | x[3];
  assign _14_ = ~((_13_ & _07_) | _12_);
  assign _15_ = ~(_13_ & _08_);
  assign _16_ = ~((_15_ | _05_) & _14_);
  assign \S4.s  = _16_ ^ _11_;
  assign _17_ = ~(y[5] ^ x[5]);
  assign _18_ = y[4] & x[4];
  assign _19_ = y[4] | x[4];
  assign _20_ = ~((_19_ & _16_) | _18_);
  assign \S5.s  = _20_ ^ _17_;
  assign _21_ = y[5] & x[5];
  assign _22_ = y[5] | x[5];
  assign _23_ = ~((_22_ & _18_) | _21_);
  assign _24_ = ~(_22_ & _19_);
  assign _25_ = _24_ | ~(_16_);
  assign \P5_1.Gij  = ~(_25_ & _23_);
  assign _00_ = y[1] ^ x[1];
  assign _01_ = y[0] & x[0];
  assign \G6.y  = y[5];
  assign \G6.x  = x[5];
  assign \G5.y  = y[4];
  assign \G5.x  = x[4];
  assign \G4.y  = y[3];
  assign \G4.x  = x[3];
  assign \G3.y  = y[2];
  assign \G3.x  = x[2];
  assign \G2.y  = y[1];
  assign \G2.x  = x[1];
  assign \G1.y  = y[0];
  assign \G1.x  = x[0];
  assign g[0] = 1'hx;
  assign h[0] = 1'hx;
  assign p[0] = 1'hx;
  assign s = { \P5_1.Gij , \S5.s , \S4.s , \S3.s , \S2.s , \S1.s , \G1.h  };
endmodule
