/* Generated by Yosys 0.9 (git sha1 1979e0b) */
`include "cmos_cells.v"
(* top =  1  *)
(* src = "sumator.v:29" *)
module adder(\x[0] , \x[1] , \x[2] , \x[3] , \x[4] , \x[5] , \y[0] , \y[1] , \y[2] , \y[3] , \y[4] , \y[5] , \s[0] , \s[1] , \s[2] , \s[3] , \s[4] , \s[5] , \s[6] );
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  (* src = "sumator.v:47|sumator.v:5" *)
  wire \G1.h ;
  (* src = "sumator.v:47|sumator.v:2" *)
  wire \G1.x ;
  (* src = "sumator.v:47|sumator.v:2" *)
  wire \G1.y ;
  (* src = "sumator.v:48|sumator.v:2" *)
  wire \G2.x ;
  (* src = "sumator.v:48|sumator.v:2" *)
  wire \G2.y ;
  (* src = "sumator.v:49|sumator.v:2" *)
  wire \G3.x ;
  (* src = "sumator.v:49|sumator.v:2" *)
  wire \G3.y ;
  (* src = "sumator.v:50|sumator.v:2" *)
  wire \G4.x ;
  (* src = "sumator.v:50|sumator.v:2" *)
  wire \G4.y ;
  (* src = "sumator.v:51|sumator.v:2" *)
  wire \G5.x ;
  (* src = "sumator.v:51|sumator.v:2" *)
  wire \G5.y ;
  (* src = "sumator.v:52|sumator.v:2" *)
  wire \G6.x ;
  (* src = "sumator.v:52|sumator.v:2" *)
  wire \G6.y ;
  (* src = "sumator.v:90|sumator.v:14" *)
  wire \P5_1.Gij ;
  (* src = "sumator.v:66|sumator.v:22" *)
  wire \S1.s ;
  (* src = "sumator.v:73|sumator.v:22" *)
  wire \S2.s ;
  (* src = "sumator.v:77|sumator.v:22" *)
  wire \S3.s ;
  (* src = "sumator.v:82|sumator.v:22" *)
  wire \S4.s ;
  (* src = "sumator.v:86|sumator.v:22" *)
  wire \S5.s ;
  (* src = "sumator.v:37" *)
  wire \g[0] ;
  (* src = "sumator.v:35" *)
  wire \h[0] ;
  (* src = "sumator.v:36" *)
  wire \p[0] ;
  (* src = "sumator.v:33" *)
  output \s[0] ;
  (* src = "sumator.v:33" *)
  output \s[1] ;
  (* src = "sumator.v:33" *)
  output \s[2] ;
  (* src = "sumator.v:33" *)
  output \s[3] ;
  (* src = "sumator.v:33" *)
  output \s[4] ;
  (* src = "sumator.v:33" *)
  output \s[5] ;
  (* src = "sumator.v:33" *)
  output \s[6] ;
  (* src = "sumator.v:31" *)
  input \x[0] ;
  (* src = "sumator.v:31" *)
  input \x[1] ;
  (* src = "sumator.v:31" *)
  input \x[2] ;
  (* src = "sumator.v:31" *)
  input \x[3] ;
  (* src = "sumator.v:31" *)
  input \x[4] ;
  (* src = "sumator.v:31" *)
  input \x[5] ;
  (* src = "sumator.v:32" *)
  input \y[0] ;
  (* src = "sumator.v:32" *)
  input \y[1] ;
  (* src = "sumator.v:32" *)
  input \y[2] ;
  (* src = "sumator.v:32" *)
  input \y[3] ;
  (* src = "sumator.v:32" *)
  input \y[4] ;
  (* src = "sumator.v:32" *)
  input \y[5] ;
  NOT _071_ (
    .A(\y[1] ),
    .Y(_000_)
  );
  NOT _072_ (
    .A(\x[1] ),
    .Y(_001_)
  );
  NOT _073_ (
    .A(\y[3] ),
    .Y(_002_)
  );
  NOT _074_ (
    .A(\x[3] ),
    .Y(_003_)
  );
  NOT _075_ (
    .A(\y[2] ),
    .Y(_004_)
  );
  NOT _076_ (
    .A(\x[2] ),
    .Y(_005_)
  );
  NOT _077_ (
    .A(\y[4] ),
    .Y(_006_)
  );
  NOT _078_ (
    .A(\x[4] ),
    .Y(_007_)
  );
  NOT _079_ (
    .A(\y[5] ),
    .Y(_008_)
  );
  NOT _080_ (
    .A(\x[5] ),
    .Y(_009_)
  );
  NOT _081_ (
    .A(\y[0] ),
    .Y(_010_)
  );
  NOT _082_ (
    .A(\x[0] ),
    .Y(_011_)
  );
  NOR _083_ (
    .A(\y[2] ),
    .B(\x[2] ),
    .Y(_012_)
  );
  NAND _084_ (
    .A(_004_),
    .B(_005_),
    .Y(_013_)
  );
  NOR _085_ (
    .A(_004_),
    .B(_005_),
    .Y(_014_)
  );
  NAND _086_ (
    .A(\y[2] ),
    .B(\x[2] ),
    .Y(_015_)
  );
  NOR _087_ (
    .A(_012_),
    .B(_014_),
    .Y(_016_)
  );
  NAND _088_ (
    .A(_013_),
    .B(_015_),
    .Y(_017_)
  );
  NOR _089_ (
    .A(_000_),
    .B(_001_),
    .Y(_018_)
  );
  NAND _090_ (
    .A(\y[1] ),
    .B(\x[1] ),
    .Y(_019_)
  );
  NOR _091_ (
    .A(\y[1] ),
    .B(\x[1] ),
    .Y(_020_)
  );
  NOT _092_ (
    .A(_020_),
    .Y(_021_)
  );
  NOR _093_ (
    .A(_010_),
    .B(_011_),
    .Y(_022_)
  );
  NAND _094_ (
    .A(\y[0] ),
    .B(\x[0] ),
    .Y(_023_)
  );
  NOR _095_ (
    .A(_020_),
    .B(_023_),
    .Y(_024_)
  );
  NOT _096_ (
    .A(_024_),
    .Y(_025_)
  );
  NOR _097_ (
    .A(_018_),
    .B(_024_),
    .Y(_026_)
  );
  NAND _098_ (
    .A(_019_),
    .B(_025_),
    .Y(_027_)
  );
  NAND _099_ (
    .A(_017_),
    .B(_027_),
    .Y(_028_)
  );
  NAND _100_ (
    .A(_016_),
    .B(_026_),
    .Y(_029_)
  );
  NAND _101_ (
    .A(_028_),
    .B(_029_),
    .Y(\s[2] )
  );
  NOR _102_ (
    .A(_002_),
    .B(_003_),
    .Y(_030_)
  );
  NAND _103_ (
    .A(\y[3] ),
    .B(\x[3] ),
    .Y(_031_)
  );
  NOR _104_ (
    .A(\y[3] ),
    .B(\x[3] ),
    .Y(_032_)
  );
  NAND _105_ (
    .A(_002_),
    .B(_003_),
    .Y(_033_)
  );
  NOR _106_ (
    .A(_030_),
    .B(_032_),
    .Y(_034_)
  );
  NOR _107_ (
    .A(_012_),
    .B(_026_),
    .Y(_035_)
  );
  NAND _108_ (
    .A(_013_),
    .B(_027_),
    .Y(_036_)
  );
  NOR _109_ (
    .A(_014_),
    .B(_035_),
    .Y(_037_)
  );
  NAND _110_ (
    .A(_015_),
    .B(_036_),
    .Y(_038_)
  );
  NOR _111_ (
    .A(_034_),
    .B(_038_),
    .Y(_039_)
  );
  NOR _112_ (
    .A(_032_),
    .B(_037_),
    .Y(_040_)
  );
  NAND _113_ (
    .A(_033_),
    .B(_038_),
    .Y(_041_)
  );
  NOR _114_ (
    .A(_030_),
    .B(_041_),
    .Y(_042_)
  );
  NOR _115_ (
    .A(_039_),
    .B(_042_),
    .Y(\s[3] )
  );
  NOR _116_ (
    .A(\y[4] ),
    .B(\x[4] ),
    .Y(_043_)
  );
  NAND _117_ (
    .A(_006_),
    .B(_007_),
    .Y(_044_)
  );
  NOR _118_ (
    .A(_006_),
    .B(_007_),
    .Y(_045_)
  );
  NAND _119_ (
    .A(\y[4] ),
    .B(\x[4] ),
    .Y(_046_)
  );
  NOR _120_ (
    .A(_043_),
    .B(_045_),
    .Y(_047_)
  );
  NAND _121_ (
    .A(_044_),
    .B(_046_),
    .Y(_048_)
  );
  NOR _122_ (
    .A(_030_),
    .B(_040_),
    .Y(_049_)
  );
  NAND _123_ (
    .A(_031_),
    .B(_041_),
    .Y(_050_)
  );
  NAND _124_ (
    .A(_047_),
    .B(_049_),
    .Y(_051_)
  );
  NAND _125_ (
    .A(_048_),
    .B(_050_),
    .Y(_052_)
  );
  NAND _126_ (
    .A(_051_),
    .B(_052_),
    .Y(\s[4] )
  );
  NOR _127_ (
    .A(\y[5] ),
    .B(\x[5] ),
    .Y(_053_)
  );
  NAND _128_ (
    .A(_008_),
    .B(_009_),
    .Y(_054_)
  );
  NAND _129_ (
    .A(\y[5] ),
    .B(\x[5] ),
    .Y(_055_)
  );
  NOT _130_ (
    .A(_055_),
    .Y(_056_)
  );
  NOR _131_ (
    .A(_053_),
    .B(_056_),
    .Y(_057_)
  );
  NAND _132_ (
    .A(_054_),
    .B(_055_),
    .Y(_058_)
  );
  NOR _133_ (
    .A(_043_),
    .B(_049_),
    .Y(_059_)
  );
  NAND _134_ (
    .A(_044_),
    .B(_050_),
    .Y(_060_)
  );
  NOR _135_ (
    .A(_045_),
    .B(_059_),
    .Y(_061_)
  );
  NAND _136_ (
    .A(_046_),
    .B(_060_),
    .Y(_062_)
  );
  NAND _137_ (
    .A(_058_),
    .B(_062_),
    .Y(_063_)
  );
  NAND _138_ (
    .A(_057_),
    .B(_061_),
    .Y(_064_)
  );
  NAND _139_ (
    .A(_063_),
    .B(_064_),
    .Y(\s[5] )
  );
  NAND _140_ (
    .A(_054_),
    .B(_062_),
    .Y(_065_)
  );
  NAND _141_ (
    .A(_055_),
    .B(_065_),
    .Y(\s[6] )
  );
  NOR _142_ (
    .A(_018_),
    .B(_020_),
    .Y(_066_)
  );
  NAND _143_ (
    .A(_019_),
    .B(_021_),
    .Y(_067_)
  );
  NOR _144_ (
    .A(_022_),
    .B(_066_),
    .Y(_068_)
  );
  NOR _145_ (
    .A(_023_),
    .B(_067_),
    .Y(_069_)
  );
  NOR _146_ (
    .A(_068_),
    .B(_069_),
    .Y(\s[1] )
  );
  NOR _147_ (
    .A(\y[0] ),
    .B(\x[0] ),
    .Y(_070_)
  );
  NOR _148_ (
    .A(_022_),
    .B(_070_),
    .Y(\s[0] )
  );
  assign \h[0]  = 1'hx;
  assign \p[0]  = 1'hx;
  assign \G1.h  = \s[0] ;
  assign \G1.x  = \x[0] ;
  assign \G1.y  = \y[0] ;
  assign \G2.x  = \x[1] ;
  assign \G2.y  = \y[1] ;
  assign \G3.x  = \x[2] ;
  assign \G3.y  = \y[2] ;
  assign \G4.x  = \x[3] ;
  assign \G4.y  = \y[3] ;
  assign \G5.x  = \x[4] ;
  assign \G5.y  = \y[4] ;
  assign \G6.x  = \x[5] ;
  assign \G6.y  = \y[5] ;
  assign \P5_1.Gij  = \s[6] ;
  assign \S1.s  = \s[1] ;
  assign \S2.s  = \s[2] ;
  assign \S3.s  = \s[3] ;
  assign \S4.s  = \s[4] ;
  assign \S5.s  = \s[5] ;
  assign \g[0]  = 1'hx;
endmodule
